services:
  heroku-proxy-service:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${EXTERNAL_PORT}:8080"
    environment:
      - IDENTITY_SERVICE_URL=${IDENTITY_SERVICE_URL}
      - CAR_SERVICE_URL=${CAR_SERVICE_URL}
      - BOOKING_SERVICE_URL=${BOOKING_SERVICE_URL}
      - CLIENT_SERVICE_URL=${CLIENT_SERVICE_URL}
      - TICKET_SERVICE_URL=${TICKET_SERVICE_URL}
      - FILE_SERVICE_URL=${FILE_SERVICE_URL}
      - INTERNAL_SERVICE_URL=${INTERNAL_SERVICE_URL}
      - PORT=${PORT}

